#!/usr/bin/env python3
"""
Update HytaleIndustries_ItemPipe.json and HytaleIndustries_BasicItemPipe.json 
State.Definitions to map every sideConfig value (0..728) to its corresponding 
animation file generated by gen_itempipe_animations.py.

State name format: State<raw:03d>
Animation path: Blocks/Animations/ItemPipes/HytaleIndustries_ItemPipe_State_<raw:03d>.blockyanim
"""

from __future__ import annotations

import json
from pathlib import Path

ITEM_JSON = Path("src/main/resources/Server/Item/Items/HytaleIndustries_ItemPipe.json")
BASIC_ITEM_JSON = Path("src/main/resources/Server/Item/Items/HytaleIndustries_BasicItemPipe.json")
ANIM_PREFIX = "Blocks/Animations/ItemPipes/HytaleIndustries_ItemPipe_State_"


def generate_state_definitions():
    """Generate the state definitions dictionary."""
    defs = {}
    # iterate all base-4 encoded values where each digit is 0..2 (Default/Extract/None)
    for raw in range(2731):  # max raw when all digits=2 is 2730
        tmp = raw
        ok = True
        for _ in range(6):
            digit = tmp & 0b11
            if digit == 3:  # invalid (unused)
                ok = False
                break
            tmp >>= 2
        if not ok:
            continue
        name = f"State{raw:03d}"
        defs[name] = {
            "CustomModelAnimation": f"{ANIM_PREFIX}{raw:03d}.blockyanim"
        }
    return defs


def update_pipe_json(json_path: Path, state_id: str, defs: dict):
    """Update a pipe JSON file with state definitions."""
    data = json.loads(json_path.read_text(encoding="utf-8"))
    block = data.setdefault("BlockType", {})
    state = block.setdefault("State", {})
    state["Id"] = state_id
    state["Definitions"] = defs
    
    json_path.write_text(json.dumps(data, indent=2, ensure_ascii=False) + "\n", encoding="utf-8")
    print(f"Wrote {len(defs)} state definitions into {json_path}")


def main():
    defs = generate_state_definitions()
    
    # Update ItemPipe (original)
    update_pipe_json(ITEM_JSON, "itemPipe", defs)
    
    # Update BasicItemPipe (new ECS version)
    update_pipe_json(BASIC_ITEM_JSON, "basicItemPipe", defs)


if __name__ == "__main__":
    main()
