#!/usr/bin/env python3
"""
Update HytaleIndustries_ItemPipe.json State.Definitions to map every sideConfig
value (0..728) to its corresponding animation file generated by
gen_itempipe_animations.py.

State name format: State<raw:03d>
Animation path: Blocks/Animations/ItemPipes/HytaleIndustries_ItemPipe_State_<raw:03d>.blockyanim
"""

from __future__ import annotations

import json
from pathlib import Path

ITEM_JSON = Path("src/main/resources/Server/Item/Items/HytaleIndustries_ItemPipe.json")
ANIM_PREFIX = "Blocks/Animations/ItemPipes/HytaleIndustries_ItemPipe_State_"


def main():
    data = json.loads(ITEM_JSON.read_text(encoding="utf-8"))
    block = data.setdefault("BlockType", {})
    state = block.setdefault("State", {})
    state["Id"] = "itemPipe"

    defs = {}
    # iterate all base-4 encoded values where each digit is 0..2 (Default/Extract/None)
    for raw in range(2731):  # max raw when all digits=2 is 2730
        tmp = raw
        ok = True
        for _ in range(6):
            digit = tmp & 0b11
            if digit == 3:  # invalid (unused)
                ok = False
                break
            tmp >>= 2
        if not ok:
            continue
        name = f"State{raw:03d}"
        defs[name] = {
            "CustomModelAnimation": f"{ANIM_PREFIX}{raw:03d}.blockyanim"
        }

    state["Definitions"] = defs

    ITEM_JSON.write_text(json.dumps(data, indent=2, ensure_ascii=False) + "\n", encoding="utf-8")
    print(f"Wrote {len(defs)} state definitions into {ITEM_JSON}")


if __name__ == "__main__":
    main()
